### ISSUE TITLE
modal.js

### ISSUE THREAD

**Issue by Brainybrian316** [Brainybrian316/DEVise#10]
`inside the components/ui folder`

* should hold basic modal that will be used across pages to be called in other components easily. 
* separation of concerns
``

> any styling or additional components related only too homepage should stay in the homepage folder (ex: hooks, css, etc).

**Comment by ethancahill** [comment]
@cobalt88 did you say you were going to take this? If not I will

**Comment by cobalt88** [comment]
Go for it. If you can make it accept props I can work with that
